### PR TITLE
Use the full list of emoji shortcodes

### PR DESCRIPTION
**Pull request by Nervengift**
Adds a quickphrase file for the standard-ish emoji alpha codes (EAC, emoji short codes) taken from https://github.com/Ranks/emoji-alpha-codes
Also removes the juila REPL emoji introduced by 20c65a8 since they are a subset of these.

### CODE REVIEW

**Comment by yuyichao** [comment]
I don't think it's necessary to change the file name. Also, it might be better to include the MIT license of the data. (IANAL, I didn't include the julia license for my version because when I asked other julia-devs it wasn't clear if program output even need to follow the license of the program at all....)

**Comment by Nervengift** [comment]
Changing the filename shouldn't break anything, or am I missing something? And why should it be named emojl.mb, when it's not from julia anymore?

Where would I put the license?

**Comment by yuyichao** [comment]
I forgot that I renamed it to not conflict with the existing `emoji.mb` so the new name should be fine... (I suggested that mainly to make the diff easier to check, e.g. if there's any missing ones)

I believe the license requires you to include the MIT license note so I think it's should be enough to add a `COPYING.MIT` to the toplevel and include in your script (since the data file doesn't accept comment) where the data come from, which you already did, and it's license (MIT).

**Comment by Nervengift** [comment]
done

**Pull request merged**
