### PR TITLE
 when fcitxDBusWatch is null, fcitx-dbus-watch will be over 

### PR DESCRIPTION
**Pull request by chenshijie-uos**
sometimes other software will infection fcitx.

### CODE REVIEW

**Comment by wengxt** [comment]
the loop condition is already checking w is null or not.

**Comment by chenshijie-uos** [comment]
the first time w is null did not check。 realy work have the coredump。

**Comment by chenshijie-uos** [comment]
w && w-watched && other ?

**Comment by chenshijie-uos** [comment]
if (!watches){
 return ;
}

**Comment by wengxt** [comment]
> the first time w is null did not check。 realy work have the coredump。

Your coredump might be real, but the reason can't be the one you're talking about.

What you're saying is something like
for (size_t i = 0; i < vec.size(); i ++) {
}
and when size == 0 it still runs the loop body, how can that be?

**Comment by chenshijie-uos** [comment]
o  i understand ，may be i should change it to 

···
 w-watched && other ?
···

w can be null event it be null ,it can't go in there.

**Pull request closed without merging**
