### PR TITLE
Include emoji data from julia

### PR DESCRIPTION
**Pull request by yuyichao**
Including the julia script that does this, and update the corresponding installation rules to only install `*.mb` files in the quickphrase data dir.

Close https://github.com/fcitx/fcitx-table-other/issues/4

### CODE REVIEW

**Comment by yuyichao** [comment]
Not necessarily the latest data but should be good enough and easy to extract.

**Comment by wengxt** [comment]
I wonder if ":" is needed.

**Comment by yuyichao** [comment]
Mainly for namespace and be consistent with other programs/websits that support emoji input.

**Comment by wengxt** [comment]
Emm, maybe put it in a separate file name emoji-unicode.mb ?

**Comment by yuyichao** [comment]
Done

**Comment by Nervengift** [comment]
wouldn't https://github.com/Ranks/emoji-alpha-codes/blob/master/eac.csv be a better source for the emoji codes? Bigger list and kind of standard-ish…

**Comment by Nervengift** [comment]
Just created a PR for my suggestion: #262

**Comment by yuyichao** [comment]
And to answer your question here.

> Bigger list and kind of standard-ish

Better source is always welcome. AFAIK none of the other sources suggested on the issue was clearly better and when I made the PR, this is clearly the easiest to access for me.

**Pull request merged**
